=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::AuthApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthApi' do
  before do
    # run before each test
    @instance = BbceApi::AuthApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthApi' do
    it 'should create an instance of AuthApi' do
      expect(@instance).to be_instance_of(BbceApi::AuthApi)
    end
  end

  # unit tests for login
  # Authenticate the user
  # The login API is used to authenticate a user on eHub
  # @param body Data required for user login
  # @param [Hash] opts the optional parameters
  # @return [UserAuthResponse]
  describe 'login test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for login_v2
  # Authenticate the user
  # The login API is used to authenticate a user on eHub
  # @param body Data required for user login
  # @param [Hash] opts the optional parameters
  # @return [UserAuthResponse]
  describe 'login_v2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for logout
  # Logout the user
  # The Logout API is used to clear the authorization for the logged user
  # @param body Data required for user logout
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'logout test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for refresh_token
  # Update token
  # The Refresh token API is used to get new authentication token when the current token expires
  # @param body Data required to request the new token
  # @param [Hash] opts the optional parameters
  # @return [RefreshTokenResponse]
  describe 'refresh_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
