=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::CompaniesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CompaniesApi' do
  before do
    # run before each test
    @instance = BbceApi::CompaniesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CompaniesApi' do
    it 'should create an instance of CompaniesApi' do
      expect(@instance).to be_instance_of(BbceApi::CompaniesApi)
    end
  end

  # unit tests for get_company_by_id
  # Get Company by Identification
  # Get a specific company information by using a companyId
  # @param company_id 
  # @param [Hash] opts the optional parameters
  # @return [Company]
  describe 'get_company_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_company_by_id_v2
  # Get Company by Identification
  # Get a specific company information by using a companyId
  # @param company_id 
  # @param [Hash] opts the optional parameters
  # @return [Company]
  describe 'get_company_by_id_v2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_companies
  # List Companies
  # The Companies API is used when you want to receive companies information. It&#x27;s possible to specify the company or receive information on a specific status
  # @param [Hash] opts the optional parameters
  # @option opts [String] :trade_name Company trade name
  # @option opts [String] :status Company status
  # @return [Array<Company>]
  describe 'list_companies test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_companies_v2
  # List Companies
  # The Companies API is used when you want to receive companies information. It&#x27;s possible to specify the company or receive information on a specific status
  # @param [Hash] opts the optional parameters
  # @option opts [String] :trade_name Company trade name
  # @option opts [String] :status Company status
  # @return [Array<Company>]
  describe 'list_companies_v2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
