=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::ContractsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContractsApi' do
  before do
    # run before each test
    @instance = BbceApi::ContractsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContractsApi' do
    it 'should create an instance of ContractsApi' do
      expect(@instance).to be_instance_of(BbceApi::ContractsApi)
    end
  end

  # unit tests for download_contract
  # Returns a base64 string for PDF generation
  # The API is used to download a PDF file of a specific contract
  # @param contract_id Contract identifier
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_contract test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for download_contract_by_number
  # Returns a base64 string for PDF generation
  # The API is used to download a PDF file of a specific contract
  # @param contract_number Parameter contractNumber that was received in the response object of **/v1/matches** in Matches API.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'download_contract_by_number test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_customer_all_business_report
  # Returns a list of all deals
  # This API returns a list of all deals. You can filter by period or operation type
  # @param [Hash] opts the optional parameters
  # @option opts [String] :initial_period The initial ISO String Date to filter values
  # @option opts [String] :final_period The final ISO String Date to filter values
  # @option opts [Integer] :page Pagination (by default search for all elements)
  # @option opts [String] :origin_operation_type Operation Type
  # @return [Array<AllBusinessReport>]
  describe 'get_customer_all_business_report test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
