=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::CurveApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CurveApi' do
  before do
    # run before each test
    @instance = BbceApi::CurveApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurveApi' do
    it 'should create an instance of CurveApi' do
      expect(@instance).to be_instance_of(BbceApi::CurveApi)
    end
  end

  # unit tests for get_bbce_fwd_curve
  # List FWD Curve
  # List FWD Curve according to reference date
  # @param reference_date The final ISO String Date to filter values
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Pagination (by default search for all elements)
  # @return [Array<Curve>]
  describe 'get_bbce_fwd_curve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
