=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::DetailedRegistriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DetailedRegistriesApi' do
  before do
    # run before each test
    @instance = BbceApi::DetailedRegistriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DetailedRegistriesApi' do
    it 'should create an instance of DetailedRegistriesApi' do
      expect(@instance).to be_instance_of(BbceApi::DetailedRegistriesApi)
    end
  end

  # unit tests for create_detailed_registry
  # Create a detailed registry
  # This API is used when you want to create a detailed registry, witch means this registry can be customized whereas the standard registry cannot
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Registry]
  describe 'create_detailed_registry test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
