=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::LimitsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LimitsApi' do
  before do
    # run before each test
    @instance = BbceApi::LimitsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LimitsApi' do
    it 'should create an instance of LimitsApi' do
      expect(@instance).to be_instance_of(BbceApi::LimitsApi)
    end
  end

  # unit tests for get_bilateral_company_limit
  # Get current limit between companies
  # This API is used to control a bilateral limit between companies. You can get current purchase and sale consume limit and its percentage
  # @param product_link_id Product Link identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<BilateralCompanyLimit>]
  describe 'get_bilateral_company_limit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_bilateral_company_limit
  # Create a ProductLink Bilateral Limit between companies
  # This API is used to create a new bilateral limit between companies
  # @param body Create a ProductLink Bilateral Limit between companies
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'post_bilateral_company_limit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
