=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::LinkApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LinkApi' do
  before do
    # run before each test
    @instance = BbceApi::LinkApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinkApi' do
    it 'should create an instance of LinkApi' do
      expect(@instance).to be_instance_of(BbceApi::LinkApi)
    end
  end

  # unit tests for get_link
  # Returns the list of links with product feature and underlying asset
  # Returns the list of links with product feature and underlying asset
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Pagination (by default search for all elements)
  # @option opts [Integer] :items_per_page Number of items per page (default 10)
  # @return [Array<ProductLink>]
  describe 'get_link test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
