=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::OrdersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OrdersApi' do
  before do
    # run before each test
    @instance = BbceApi::OrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrdersApi' do
    it 'should create an instance of OrdersApi' do
      expect(@instance).to be_instance_of(BbceApi::OrdersApi)
    end
  end

  # unit tests for activate_order
  # Activate a suspended order
  # This API is used when you want a specific suspended order to be active again. In this case, the order will return as opened
  # @param ticker_id Ticker identifier number.   Parameter **id** that was received in the response object of **/v2/tickers** in Negotiation API
  # @param order_id Order identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'activate_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for activate_orders_in_batch
  # Activate suspended orders
  # This API is used when you want all suspended orders of a specific Wallet to be activate
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'activate_orders_in_batch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cancel_order
  # Cancel a suspended or opened order
  # This API is used to cancel an order. The order must be open or suspended in order to cancel it
  # @param ticker_id Ticker identifier number.   Parameter **id** that was received in the response object of **/v2/tickers** in Negotiation API
  # @param order_id Order identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cancel_orders_in_batch
  # Cancel all suspended or opened orders
  # This API is used to cancel all opened and suspended company&#x27;s orders
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cancel_orders_in_batch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_purchase_order
  # Create a purchase order
  # This API is used to create a purchase order
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'create_purchase_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_sales_order
  # Create a sales order
  # This API is used to create a sales order
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'create_sales_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for edit_order
  # Edit a suspended or opened order
  # This API is used to edit an order. You can only edit opened or suspended orders
  # @param body 
  # @param order_id Order identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'edit_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_book
  # Return the current book for given ticker
  # This API is used to receive the current book for a specific ticker
  # @param ticker_id Ticker identifier number.   Parameter **id** that was received in the response object of **/v2/tickers** in Negotiation API
  # @param wallet_id Wallet identifier number.   Parameter **id** that was received in the response object of **/v1/wallets** in Wallets API
  # @param [Hash] opts the optional parameters
  # @return [OffersBook]
  describe 'get_book test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_negotiation_data
  # Return the daily negotiation prices for given ticker
  # This API is used to receive daily negotiation prices for a giver ticker. You will receive minimum, maximum, first and last prices
  # @param ticker_id Ticker identifier number.   Parameter **id** that was received in the response object of **/v2/tickers** in Negotiation API
  # @param [Hash] opts the optional parameters
  # @return [NegotiationData]
  describe 'get_negotiation_data test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_orders
  # Return list of my own orders
  # This API returns a list of user&#x27;s own orders. You can filter by period or a specific status
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :product_id Product identifier not obligatory
  # @option opts [Integer] :link_id Stamp Product identifier
  # @option opts [String] :initial_period The initial ISO String Date to filter values
  # @option opts [String] :final_period The final ISO String Date to filter values
  # @option opts [String] :status Order status
  # @option opts [String] :position Purchase or Sales order operation type
  # @option opts [String] :last_resource_key Primary key of the last resource returned
  # @return [Array<OrderReport>]
  describe 'get_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for suspend_order
  # Suspend an opened order
  # This API is used when you want to suspend an opened order
  # @param ticker_id Ticker identifier number.   Parameter **id** that was received in the response object of **/v2/tickers** in Negotiation API
  # @param order_id Order identifier
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'suspend_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for suspend_orders_in_batch
  # Suspend opened orders
  # This API is used to suspend all opened orders of a specific wallet
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'suspend_orders_in_batch test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
