=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::RegistriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RegistriesApi' do
  before do
    # run before each test
    @instance = BbceApi::RegistriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RegistriesApi' do
    it 'should create an instance of RegistriesApi' do
      expect(@instance).to be_instance_of(BbceApi::RegistriesApi)
    end
  end

  # unit tests for approve_registry
  # Approve a registry
  # This API is used when a counterparty creates a registry with you. To complete the Deal you will need to approve it
  # @param body 
  # @param registry_id Registry identifier
  # @param [Hash] opts the optional parameters
  # @return [Registry]
  describe 'approve_registry test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_registry
  # Create a registry
  # The Registry API is used when you want to create a standard registry. You need to inform your counterparty the moment you create your registry
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [Registry]
  describe 'create_registry test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_registries
  # Returns list of registries
  # This API returns a list of registries of a specific wallet. You can filter by date
  # @param wallet_id Wallet identifier number.   Parameter **id** that was received in the response object of **/v1/wallets** in Wallets API
  # @param [Hash] opts the optional parameters
  # @option opts [String] :end_date The final ISO String Date to filter values
  # @option opts [String] :start_date The initial ISO String Date to filter values
  # @option opts [String] :last_resource_key Primary key of the last resource returned
  # @return [Array<Registry>]
  describe 'list_registries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
