=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BbceApi::WalletsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WalletsApi' do
  before do
    # run before each test
    @instance = BbceApi::WalletsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WalletsApi' do
    it 'should create an instance of WalletsApi' do
      expect(@instance).to be_instance_of(BbceApi::WalletsApi)
    end
  end

  # unit tests for list_wallets
  # List all wallets that can be operated by current user
  # @param [Hash] opts the optional parameters
  # @return [Array<Wallet>]
  describe 'list_wallets test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
