=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BbceApi::AllBusinessStatus
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AllBusinessStatus' do
  before do
    # run before each test
    @instance = BbceApi::AllBusinessStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllBusinessStatus' do
    it 'should create an instance of AllBusinessStatus' do
      expect(@instance).to be_instance_of(BbceApi::AllBusinessStatus)
    end
  end
end
