=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BbceApi::DeadlineValuePayload
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeadlineValuePayload' do
  before do
    # run before each test
    @instance = BbceApi::DeadlineValuePayload.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeadlineValuePayload' do
    it 'should create an instance of DeadlineValuePayload' do
      expect(@instance).to be_instance_of(BbceApi::DeadlineValuePayload)
    end
  end
  describe 'test attribute "deadline_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["M", "Y"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.deadline_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "deadline_begin"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "deadline_end"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "limit_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
