=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BbceApi::OperationStatus
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OperationStatus' do
  before do
    # run before each test
    @instance = BbceApi::OperationStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OperationStatus' do
    it 'should create an instance of OperationStatus' do
      expect(@instance).to be_instance_of(BbceApi::OperationStatus)
    end
  end
end
