=begin
#BBCE Bus API

#Endpoint's specifications for routes allowed for direct client usage.

OpenAPI spec version: 1.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BbceApi::ProfileCCEE
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProfileCCEE' do
  before do
    # run before each test
    @instance = BbceApi::ProfileCCEE.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProfileCCEE' do
    it 'should create an instance of ProfileCCEE' do
      expect(@instance).to be_instance_of(BbceApi::ProfileCCEE)
    end
  end
  describe 'test attribute "id_ccee"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "agent_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "energy_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
